server:
  servlet:
    context-path: /EmpGuid
spring:
  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/empguid?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
logging:
  level:
    com.*: debug 
mybatis:
  mapper-locations:
  - classpath:/mapper/**/*.xml 
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql